// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 18/11/2025, 1:30:15 p. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/sofia/ProyectoFinal/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/ProyectoFinal/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/ProyectoFinal/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/ProyectoFinal/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/ProyectoFinal/plugins/**/*.{js,ts,mjs}","D:/sofia/ProyectoFinal/composables/**/*.{js,ts,mjs}","D:/sofia/ProyectoFinal/utils/**/*.{js,ts,mjs}","D:/sofia/ProyectoFinal/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/ProyectoFinal/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/ProyectoFinal/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/ProyectoFinal/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["11"] = "D:/sofia/ProyectoFinal/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;