// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 18/11/2025, 11:47:38 a. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/sofia/Proyecto8SofiaRafael/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/Proyecto8SofiaRafael/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/Proyecto8SofiaRafael/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/Proyecto8SofiaRafael/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/Proyecto8SofiaRafael/plugins/**/*.{js,ts,mjs}","D:/sofia/Proyecto8SofiaRafael/composables/**/*.{js,ts,mjs}","D:/sofia/Proyecto8SofiaRafael/utils/**/*.{js,ts,mjs}","D:/sofia/Proyecto8SofiaRafael/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/Proyecto8SofiaRafael/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/Proyecto8SofiaRafael/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/sofia/Proyecto8SofiaRafael/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["11"] = "D:/sofia/Proyecto8SofiaRafael/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;